door1.normal.grant.msecs=6250
door1.extended.grant.msecs=18750
door1.min.open.msecs=0000
relay1.min.open.msecs=6250
relay2.min.open.msecs=0000
door1.held.grace.interval.msecs=37500
rex1.open.msecs=6250
aux1.min.open.msecs=0000
aux2.min.open.msecs=0000
v200.relay1.min.open.msecs=6250
v200.relay2.min.open.msecs=6250
v100.relay1.min.open.msecs=6250
rex.1.unlocks.door=true
card.in.free.out.enabled=true
function.0.18.enabled=false
function.0.2.enabled=false
function.0.0.enabled=false
function.1.0.enabled=false
function.0.1.enabled=true
function.1.1.enabled=false
function.4.0.enabled=false
a-d.0.2.enabled=true
a-d.0.2.inputNum=0
a-d.0.1.enabled=true
a-d.0.1.inputNum=0
a-d.1.1.enabled=true
a-d.1.1.inputNum=0
a-d.0.23.enabled=true
a-d.0.23.inputNum=0
a-d.0.22.enabled=true
a-d.0.22.inputNum=7
a-d.0.21.enabled=true
a-d.0.21.inputNum=0
a-d.0.20.enabled=true
a-d.0.20.inputNum=6
a-d.0.13.enabled=true
a-d.0.13.inputNum=0
a-d.0.12.enabled=true
a-d.0.12.inputNum=2
a-d.0.9.enabled=true
a-d.0.9.inputNum=0
a-d.0.8.enabled=true
a-d.0.8.inputNum=0
function.0.14.enabled=false
function.0.9.enabled=false
function.0.11.enabled=false
function.0.3.enabled=false
function.0.4.enabled=false
function.0.27.enabled=true
function.0.16.enabled=false
function.0.19.enabled=true
function.0.30.enabled=true
